- name: 'ping'
  description: 'ping'
  type: 'text'
  data: 'pong'

- name: 'checkmark'
  description: 'test checkmark'
  type: 'image'
  data: 'https://test-ipv6.com/images/hires_ok.png'

- name: 'audio'
  description: '440Hz Audio Test'
  type: 'audio'
  data: './samples/400hz.wav'

- name: 'help'
  description: 'displays a list of commands'
  type: 'custom'
  data: './commands/help.js'
- name: 'clean'
  description: 'cleans channel'
  type: 'custom'
  data: './commands/clean.js'
- name: 'evil-insult'
  description: 'sends an insult from evilinsult.com'
  type: 'custom'
  data: './commands/evilInsult.js'
- name: 'owo'
  description: "replaces text based on OwO chrome extension"
  type: 'custom'
  data: './commands/owo.js'
- name: 'shiba'
  description: 'random shiba from shibe.online'
  type: 'custom'
  data: './commands/shiba.js'
- name: 'cat'
  description: 'random cat from random.cat'
  type: 'custom'
  data: './commands/cat.js'
- name: 'fox'
  description: 'random fox from randomfox.ca'
  type: 'custom'
  data: './commands/fox.js'
- name: 'dog'
  description: 'random dog from random.dog'
  type: 'custom'
  data: './commands/dog.js'